name: maply
description: Maply
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-262.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^6.0.0
  get_it_hooks: ^2.0.0
  flutter_hooks: ^0.16.0
  google_maps_flutter: ^2.1.0
  geolocator: ^7.7.1
  material_floating_search_bar: ^0.3.6
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: launcher_icon
  adaptive_icon_background: "#181A20"
  adaptive_icon_foreground: assets/icon/Maply-Foreground.png
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon/MAply.png

flutter:
  uses-material-design: true
  fonts:
      - family: Comfortaa
        fonts:
          - asset: assets/font/Comfortaa.ttf